#!/bin/bash

input="$1"
output="$2"

if [ ! -f "$input" ]; then
  echo "error: <inpput> file not found ('$input')"
  exit 1
elif [ -z "$output" ]; then
  echo "error: missing <output> argument"
  exit 1
fi

pandoc "$input" \
  --resource-path="$(dirname "$input")" \
  --from markdown-smart \
  --highlight-style=style-document.theme \
  -V mainfont="Baskerville Regular" \
  -V monofont="IBM Plex Mono Regular" \
  -V colorlinks=true \
  -V linkcolor=blue \
  -V urlcolor=blue \
  -V anchorcolor=blue \
  -V toccolor=gray \
  -V geometry="margin=3.5cm" \
  -V linestretch="1.1" \
  -o "$output"
